//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanlaptop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GOPY
    {
        public int MAGOPY { get; set; }
        public string TEN { get; set; }
        public string NOIDUNG { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> NGAYGUI { get; set; }
        public bool TRANGTHAI { get; set; }
    }
}
